language: ruby
rvm:
  - 1.8.7
  - 2.0.0
script: 'bundle exec rake spec'
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3"
gemfile: .gemfile
matrix:
    fast_finish: true
    allow_failures:
        - rvm: 2.0.0
    exclude:
        - rvm: 2.0.0
          env: PUPPET_VERSION="~> 2.7.0"
notifications:
  email: false
